on: push
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2

    # - name: Install Dependencies
    #   run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # above tut recorded
    # - name: Setup PHP with PECL extension
    #   uses: shivammathur/setup-php@v2
    #   with:
    #     php-version: '8.0'

    - name: Set up Node
        run: |
          npm install
          npm run build


    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.biztechsols.co.uk
        username: biztechsols.co.uk
        password: 7ba35455b2a5
        server-dir: /public_html/laravel-demo/
        protocol: ftps
        # rsync-options: --dry-run --archive --verbose --compress --delete-after --human-readable --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore
